name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build
        run: ./mvnw -B -DskipTests package
      - name: Test
        run: ./mvnw -B test
      - name: Build Docker
        run: docker build -t ghcr.io/${{ github.repository }}:sha-${{ github.sha }} .
